<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Happersett_questionC.aspx.cs" Inherits="Happersett_Midterm2017_1_.WebForm3" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <h1>Movie Titles</h1>
        <asp:GridView ID="GridView1" runat="server" DataSourceID="srcMovies" DataKeyNames="MovieID" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" AutoGenerateColumns="false">
            <Columns>
                <asp:BoundField DataField="MovieID" ReadOnly="true" HeaderText="MovieID" />
                <asp:BoundField DataField="MovieTitle" HeaderText="MovieTitle" />
            </Columns>
        </asp:GridView>

        <h1> Add Movie </h1>
        <asp:DetailsView ID="DetailsView1" runat="server" DefaultMode="Insert" AutoGenerateInsertButton="true" AutoGenerateRows="false">
            <Fields>
                <asp:BoundField DataField="MovieTitle" HeaderText="MovieTitle" />
            </Fields>
        </asp:DetailsView>
        <asp:ObjectDataSource
            id="srcMovies"
            TypeName="midterm.BLL.Movie"
            SelectMethod="SelectALL"
            UpdateMethod="Update"
            InsertMethod="Insert"
            DeleteMethod="Delete"
            Runat="server" />
    </div>
    </form>
</body>
</html>
